apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-deployment
  labels:
    app: simple-html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-html
  template:
    metadata:
      labels:
        app: simple-html
    spec:
      containers:
      - name: simple-html-container
        image: puremahadi/devops-simple-html:6cc7b74313b67e610f4bdf4b487836b5a2aaf6fb
        imagePullPolicy: Always
        ports:
        - containerPort: 80

